/**
 * lib/adapters/gcal/fixture.ts — Google Calendar, simulated by one JSON file and one JSONL file.
 *
 * Owns: `GcalFixtureAdapter`, the fixture implementation of the *secondary* free/busy signal
 * (`lib/ports/freebusy.ts`). Busy blocks are read from `<fixturesDir>/calendar_busy.json`
 * (`{ worker_id, start_at, end_at, title? }[]`, generated by `lib/fixtures/gen/calendar.ts`)
 * and holds are appended to `<dataDir>/holds.jsonl`. Nothing leaves the machine.
 *
 * **This is the labelled seam (spec §4).** Meeting-level free/busy is the one availability
 * signal Rippling's API does not expose, so the POC reads Google for it and writes interview
 * holds there as a stand-in. On an internal build the whole file disappears: Rippling's own
 * calendar layer federates Google/O365 through the Workspace connector and already holds
 * Rippling-native events (PTO, holidays, interviews booked by Smart Scheduling), and the
 * hold becomes a **Smart Scheduling** call rather than an event insert.
 *
 * A caller must never hold this object directly: `lib/availability/compose.ts` puts Rippling
 * absence in front of it so a free calendar can never book somebody who is on leave.
 *
 * Public interface: `GcalFixtureAdapter` (implements `FreeBusyPort`), `GcalFixtureOptions`,
 * `HoldLine`, `CALENDAR_BUSY_FILE`, `HOLDS_FILENAME`, `readCalendarBusy`.
 *
 * Google calls this stands in for: calendar.freebusy.query, calendar.events.insert.
 *
 * Spec: docs/SPEC.md §2, §4, §8 loop 2, §9; docs/PLAN.md §2.3, §2.8, §5 block B2.1.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { appendJsonLine, randomHex, toInstant } from '#lib/adapters/fixture/ledger.ts';
import type { CalendarBusyRow } from '#lib/fixtures/gen/bundle.ts';
import type { HoldInput, HoldResult, Slot } from '#lib/ports/availability.ts';
import type { BusyBlock, BusyRange, FreeBusyPort } from '#lib/ports/freebusy.ts';
import type { InstantISO, WorkerId } from '#lib/types/tier1.ts';

/** The fixture free/busy table, relative to `TL_FIXTURES_DIR`. */
export const CALENDAR_BUSY_FILE = 'calendar_busy.json';

/** Where placed holds land, relative to `TL_DATA_DIR`. */
export const HOLDS_FILENAME = 'holds.jsonl';

/** One placed hold. The agent books as the acting user, never as itself (spec §9). */
export interface HoldLine {
  ts: InstantISO;
  hold_ref: string;
  /** Acting worker the hold was created by. */
  actor: WorkerId;
  title: string;
  start_at: InstantISO;
  end_at: InstantISO;
  attendees: WorkerId[];
}

export interface GcalFixtureOptions {
  /** Read-only fixtures dir holding `calendar_busy.json`. Ignored when `rows` is given. */
  fixturesDir?: string;
  /** Runtime dir the holds file is appended to (`TL_DATA_DIR`). */
  dataDir: string;
  /** Worker id the agent acts as; recorded on every hold. */
  actorWorkerId: WorkerId;
  /** The (frozen) clock. */
  now: () => Date;
  /** Pre-loaded busy rows (the tenant bundle already has them); avoids a second disk read. */
  rows?: readonly CalendarBusyRow[];
}

/** Read `calendar_busy.json` from a fixtures dir. A missing file is an empty calendar. */
export function readCalendarBusy(fixturesDir: string): CalendarBusyRow[] {
  const path = join(fixturesDir, CALENDAR_BUSY_FILE);
  if (!existsSync(path)) return [];
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'));
  return Array.isArray(parsed) ? (parsed as CalendarBusyRow[]) : [];
}

/** `true` when a row overlaps `[from, to)`. Touching edges do not overlap. */
function overlaps(row: CalendarBusyRow, from: string, to: string): boolean {
  return row.start_at < to && row.end_at > from;
}

export class GcalFixtureAdapter implements FreeBusyPort {
  private readonly holdsPath: string;
  private readonly actorWorkerId: WorkerId;
  private readonly now: () => Date;
  private readonly fixturesDir: string | undefined;
  private rows: CalendarBusyRow[] | undefined;

  constructor(options: GcalFixtureOptions) {
    this.holdsPath = join(options.dataDir, HOLDS_FILENAME);
    this.actorWorkerId = options.actorWorkerId;
    this.now = options.now;
    this.fixturesDir = options.fixturesDir;
    this.rows = options.rows === undefined ? undefined : [...options.rows];
  }

  /** Lazily loaded, then cached: a tick asks for free/busy more than once. */
  private busyRows(): CalendarBusyRow[] {
    if (this.rows === undefined) {
      this.rows = this.fixturesDir === undefined ? [] : readCalendarBusy(this.fixturesDir);
    }
    return this.rows;
  }

  /**
   * Busy blocks overlapping `range` for the workers asked about, sorted by start then worker
   * so the answer is deterministic. This says nothing about absence — that question belongs
   * to Rippling and is asked first by the composition (spec §4).
   */
  async busy(workerIds: WorkerId[], range: BusyRange): Promise<BusyBlock[]> {
    const wanted = new Set(workerIds);
    return this.busyRows()
      .filter((row) => wanted.has(row.worker_id) && overlaps(row, range.from, range.to))
      .map((row) => ({
        worker_id: row.worker_id,
        start_at: row.start_at,
        end_at: row.end_at,
        source: 'gcal' as const,
      }))
      .sort((a, b) =>
        a.start_at === b.start_at
          ? a.worker_id < b.worker_id
            ? -1
            : a.worker_id > b.worker_id
              ? 1
              : 0
          : a.start_at < b.start_at
            ? -1
            : 1,
      );
  }

  /**
   * Append one hold to `holds.jsonl` and return its `hold_ref`. Reached only through the
   * composed Availability port, which has already refused the booking if Rippling reports an
   * attendee away.
   */
  async placeHold(slot: Slot, input: HoldInput): Promise<HoldResult> {
    const holdRef = `hold_${randomHex(4)}`;
    const attendees = input.attendees.length > 0 ? input.attendees : slot.worker_ids;
    const line: HoldLine = {
      ts: toInstant(this.now()),
      hold_ref: holdRef,
      actor: this.actorWorkerId,
      title: input.title,
      start_at: slot.start_at,
      end_at: slot.end_at,
      attendees: [...attendees],
    };
    appendJsonLine(this.holdsPath, line);
    return { hold_ref: holdRef };
  }
}
